import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const games = trpc.game.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="my-20 mx-auto h-4/6 max-w-7xl rounded bg-white">
        <div className="border-b-grey-300 border border-t p-5">
          <nav className="flex w-full flex-row gap-4">
            <Link href={"/"}>Hues &amp; Cues</Link>
            <Link href={"/game/new"}>New game</Link>
          </nav>
        </div>
        <main className="p-5">
          {games.data?.games.map((game) => (
            <div key={game.uuid}>
              <Image
                src={`https://fen2image.chessvision.ai/${game.fen}`}
                width={200}
                height={200}
                alt=""
              />
            </div>
          ))}
        </main>
      </header>
    </>
  );
};

export default Home;
