import type { Game } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import { env } from "../env/client.mjs";

const Home: NextPage = () => {
  const { data } = trpc.game.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-20 mx-auto h-4/6 max-w-7xl rounded bg-black">
        <header className="border-b border-b-gray-400 p-5">
          <nav className="flex w-full flex-row justify-between gap-4">
            <Link className="text-white" href={"/"}>
              Chess Game Annotator
            </Link>
            <button className="text-white">Refresh games</button>
          </nav>
        </header>
        <main className="p-5">
          {data &&
            data.map((game: Game) => (
              <div
                className="flex flex-row border-b border-b-gray-400 py-5"
                key={game.id}
              >
                <Link href={game.url} target="_blank">
                  <Image
                    src={`https://fen2image.chessvision.ai/${game.fen}`}
                    width={200}
                    height={200}
                    alt=""
                  />
                </Link>

                <div className="flex grow flex-col items-center justify-center">
                  <p className="text-white">
                    {env.NEXT_PUBLIC_PLAYER_USERNAME}
                  </p>
                  <p className="text-white">vs</p>
                  <p className="text-white">{game.opponentName}</p>
                </div>
                <div className="w-2/5 border-l border-l-gray-400 p-5">
                  {game.learning !== "" ? (
                    <p>{game.learning}</p>
                  ) : (
                    <div className="flex h-full items-center justify-center">
                      <Link
                        className="rounded border border-b-gray-400 p-2 text-white"
                        href={`/game/${game.id}`}
                      >
                        Add learning here
                      </Link>
                    </div>
                  )}
                </div>
              </div>
            ))}
        </main>
      </div>
    </>
  );
};

export default Home;
